# Generated by Django 3.0.5 on 2023-10-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom5',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
